include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true
    unawaited_futures: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
